porter-stemmer docStop\AbassiM.stp > docStem\AbassiM.stm
porter-stemmer docStop\AgricoleW.stp > docStem\AgricoleW.stm
porter-stemmer docStop\AliR.stp > docStem\AliR.stm
porter-stemmer docStop\AngCX.stp > docStem\AngCX.stm
porter-stemmer docStop\AngeloZ.stp > docStem\AngeloZ.stm
porter-stemmer docStop\AppadooD.stp > docStem\AppadooD.stm
porter-stemmer docStop\BenHasineA.stp > docStem\BenHasineA.stm
porter-stemmer docStop\BenssiN.stp > docStem\BenssiN.stm
porter-stemmer docStop\BhagatR.stp > docStem\BhagatR.stm
porter-stemmer docStop\BradyE.stp > docStem\BradyE.stm
porter-stemmer docStop\BriarsC.stp > docStem\BriarsC.stm
porter-stemmer docStop\Broadhurst.stp > docStem\Broadhurst.stm
porter-stemmer docStop\BronksA.stp > docStem\BronksA.stm
porter-stemmer docStop\BrownL.stp > docStem\BrownL.stm
porter-stemmer docStop\ChanaG.stp > docStem\ChanaG.stm
porter-stemmer docStop\ChanCK.stp > docStem\ChanCK.stm
porter-stemmer docStop\ChanWK.stp > docStem\ChanWK.stm
porter-stemmer docStop\CheangF.stp > docStem\CheangF.stm
porter-stemmer docStop\ChengLC.stp > docStem\ChengLC.stm
porter-stemmer docStop\ChewCH.stp > docStem\ChewCH.stm
porter-stemmer docStop\ChongJYH.stp > docStem\ChongJYH.stm
porter-stemmer docStop\ChongKV.stp > docStem\ChongKV.stm
porter-stemmer docStop\ChongL.stp > docStem\ChongL.stm
porter-stemmer docStop\CollingsM.stp > docStem\CollingsM.stm
porter-stemmer docStop\CollisC.stp > docStem\CollisC.stm
porter-stemmer docStop\DiamantopoulosG.stp > docStem\DiamantopoulosG.stm
porter-stemmer docStop\DongP.stp > docStem\DongP.stm
porter-stemmer docStop\EdwinO.stp > docStem\EdwinO.stm
porter-stemmer docStop\EftekhariS.stp > docStem\EftekhariS.stm
porter-stemmer docStop\EvansA.stp > docStem\EvansA.stm
porter-stemmer docStop\FooKSNEW.stp > docStem\FooKSNEW.stm
porter-stemmer docStop\Form.stp > docStem\Form.stm
porter-stemmer docStop\HaskellS.stp > docStem\HaskellS.stm
porter-stemmer docStop\HayatB.stp > docStem\HayatB.stm
porter-stemmer docStop\HengKK.stp > docStem\HengKK.stm
porter-stemmer docStop\HicksJ.stp > docStem\HicksJ.stm
porter-stemmer docStop\HoJW.stp > docStem\HoJW.stm
porter-stemmer docStop\HowlettA.stp > docStem\HowlettA.stm
porter-stemmer docStop\HughesP.stp > docStem\HughesP.stm
porter-stemmer docStop\JavaidMT.stp > docStem\JavaidMT.stm
porter-stemmer docStop\JiangS.stp > docStem\JiangS.stm
porter-stemmer docStop\JohalS.stp > docStem\JohalS.stm
porter-stemmer docStop\KallayT.stp > docStem\KallayT.stm
porter-stemmer docStop\KhanS.stp > docStem\KhanS.stm
porter-stemmer docStop\KhayumM.stp > docStem\KhayumM.stm
porter-stemmer docStop\KijakM.stp > docStem\KijakM.stm
porter-stemmer docStop\KoL.stp > docStem\KoL.stm
porter-stemmer docStop\KupusamyS.stp > docStem\KupusamyS.stm
porter-stemmer docStop\LaiYK.stp > docStem\LaiYK.stm
porter-stemmer docStop\LamC.stp > docStem\LamC.stm
porter-stemmer docStop\LamD.stp > docStem\LamD.stm
porter-stemmer docStop\LauEWF.stp > docStem\LauEWF.stm
porter-stemmer docStop\LeongJ.stp > docStem\LeongJ.stm
porter-stemmer docStop\LiC.stp > docStem\LiC.stm
porter-stemmer docStop\LimCL.stp > docStem\LimCL.stm
porter-stemmer docStop\LimSL.stp > docStem\LimSL.stm
porter-stemmer docStop\LimS.stp > docStem\LimS.stm
porter-stemmer docStop\LingLH.stp > docStem\LingLH.stm
porter-stemmer docStop\LoH.stp > docStem\LoH.stm
porter-stemmer docStop\LokCY.stp > docStem\LokCY.stm
porter-stemmer docStop\LoV.stp > docStem\LoV.stm
porter-stemmer docStop\McCardleR.stp > docStem\McCardleR.stm
porter-stemmer docStop\McKayM.stp > docStem\McKayM.stm
porter-stemmer docStop\MohdNasir.stp > docStem\MohdNasir.stm
porter-stemmer docStop\MohdSarit.stp > docStem\MohdSarit.stm
porter-stemmer docStop\MoN.stp > docStem\MoN.stm
porter-stemmer docStop\MorganC.stp > docStem\MorganC.stm
porter-stemmer docStop\MurrianR.stp > docStem\MurrianR.stm
porter-stemmer docStop\NelsonJ.stp > docStem\NelsonJ.stm
porter-stemmer docStop\NgTA.stp > docStem\NgTA.stm
porter-stemmer docStop\NgWC.stp > docStem\NgWC.stm
porter-stemmer docStop\NyagoA.stp > docStem\NyagoA.stm
porter-stemmer docStop\OkorieV.stp > docStem\OkorieV.stm
porter-stemmer docStop\OlomofeO.stp > docStem\OlomofeO.stm
porter-stemmer docStop\PalmerG.stp > docStem\PalmerG.stm
porter-stemmer docStop\PangCVA.stp > docStem\PangCVA.stm
porter-stemmer docStop\PangG.stp > docStem\PangG.stm
porter-stemmer docStop\PargeterA.stp > docStem\PargeterA.stm
porter-stemmer docStop\PonsamritN.stp > docStem\PonsamritN.stm
porter-stemmer docStop\PopadapoulosK.stp > docStem\PopadapoulosK.stm
porter-stemmer docStop\RajaI.stp > docStem\RajaI.stm
porter-stemmer docStop\RobertsonA.stp > docStem\RobertsonA.stm
porter-stemmer docStop\RobertsSM.stp > docStem\RobertsSM.stm
porter-stemmer docStop\RossiterJ.stp > docStem\RossiterJ.stm
porter-stemmer docStop\SamuelPNEW.stp > docStem\SamuelPNEW.stm
porter-stemmer docStop\SamuelP.stp > docStem\SamuelP.stm
porter-stemmer docStop\SchutzP.stp > docStem\SchutzP.stm
porter-stemmer docStop\ShahJ.stp > docStem\ShahJ.stm
porter-stemmer docStop\SodenJ.stp > docStem\SodenJ.stm
porter-stemmer docStop\SoonV.stp > docStem\SoonV.stm
porter-stemmer docStop\specification-Lam.stp > docStem\specification-Lam.stm
porter-stemmer docStop\SriskandarajahA.stp > docStem\SriskandarajahA.stm
porter-stemmer docStop\SwantstonD.stp > docStem\SwantstonD.stm
porter-stemmer docStop\TanPSN.stp > docStem\TanPSN.stm
porter-stemmer docStop\TanSMS.stp > docStem\TanSMS.stm
porter-stemmer docStop\TiongY.stp > docStem\TiongY.stm
porter-stemmer docStop\TngL.stp > docStem\TngL.stm
porter-stemmer docStop\TohTS.stp > docStem\TohTS.stm
porter-stemmer docStop\TomlinsonM.stp > docStem\TomlinsonM.stm
porter-stemmer docStop\TowersL.stp > docStem\TowersL.stm
porter-stemmer docStop\TsangB.stp > docStem\TsangB.stm
porter-stemmer docStop\WangMY.stp > docStem\WangMY.stm
porter-stemmer docStop\WangWS.stp > docStem\WangWS.stm
porter-stemmer docStop\WangW.stp > docStem\WangW.stm
porter-stemmer docStop\WilliamsJ.stp > docStem\WilliamsJ.stm
porter-stemmer docStop\WongCY.stp > docStem\WongCY.stm
porter-stemmer docStop\WongK.stp > docStem\WongK.stm
porter-stemmer docStop\WongWS.stp > docStem\WongWS.stm
porter-stemmer docStop\YaseenU.stp > docStem\YaseenU.stm
porter-stemmer docStop\YeapKS.stp > docStem\YeapKS.stm
porter-stemmer docStop\YiuMLM.stp > docStem\YiuMLM.stm
porter-stemmer docStop\ZhangJ.stp > docStem\ZhangJ.stm
