stop stopList50 docOrig\AbassiM.txt > docStop\AbassiM.stp
stop stopList50 docOrig\AgricoleW.txt > docStop\AgricoleW.stp
stop stopList50 docOrig\AliR.txt > docStop\AliR.stp
stop stopList50 docOrig\AngCX.txt > docStop\AngCX.stp
stop stopList50 docOrig\AngeloZ.txt > docStop\AngeloZ.stp
stop stopList50 docOrig\AppadooD.txt > docStop\AppadooD.stp
stop stopList50 docOrig\BenHasineA.txt > docStop\BenHasineA.stp
stop stopList50 docOrig\BenssiN.txt > docStop\BenssiN.stp
stop stopList50 docOrig\BhagatR.txt > docStop\BhagatR.stp
stop stopList50 docOrig\BradyE.txt > docStop\BradyE.stp
stop stopList50 docOrig\BriarsC.txt > docStop\BriarsC.stp
stop stopList50 docOrig\Broadhurst.txt > docStop\Broadhurst.stp
stop stopList50 docOrig\BronksA.txt > docStop\BronksA.stp
stop stopList50 docOrig\BrownL.txt > docStop\BrownL.stp
stop stopList50 docOrig\ChanaG.txt > docStop\ChanaG.stp
stop stopList50 docOrig\ChanCK.txt > docStop\ChanCK.stp
stop stopList50 docOrig\ChanWK.txt > docStop\ChanWK.stp
stop stopList50 docOrig\CheangF.txt > docStop\CheangF.stp
stop stopList50 docOrig\ChengLC.txt > docStop\ChengLC.stp
stop stopList50 docOrig\ChewCH.txt > docStop\ChewCH.stp
stop stopList50 docOrig\ChongJYH.txt > docStop\ChongJYH.stp
stop stopList50 docOrig\ChongKV.txt > docStop\ChongKV.stp
stop stopList50 docOrig\ChongL.txt > docStop\ChongL.stp
stop stopList50 docOrig\CollingsM.txt > docStop\CollingsM.stp
stop stopList50 docOrig\CollisC.txt > docStop\CollisC.stp
stop stopList50 docOrig\DiamantopoulosG.txt > docStop\DiamantopoulosG.stp
stop stopList50 docOrig\DongP.txt > docStop\DongP.stp
stop stopList50 docOrig\EdwinO.txt > docStop\EdwinO.stp
stop stopList50 docOrig\EftekhariS.txt > docStop\EftekhariS.stp
stop stopList50 docOrig\EvansA.txt > docStop\EvansA.stp
stop stopList50 docOrig\fileList fileList
stop stopList50 docOrig\FooKSNEW.txt > docStop\FooKSNEW.stp
stop stopList50 docOrig\Form.txt > docStop\Form.stp
stop stopList50 docOrig\HaskellS.txt > docStop\HaskellS.stp
stop stopList50 docOrig\HayatB.txt > docStop\HayatB.stp
stop stopList50 docOrig\HengKK.txt > docStop\HengKK.stp
stop stopList50 docOrig\HicksJ.txt > docStop\HicksJ.stp
stop stopList50 docOrig\HoJW.txt > docStop\HoJW.stp
stop stopList50 docOrig\HowlettA.txt > docStop\HowlettA.stp
stop stopList50 docOrig\HughesP.txt > docStop\HughesP.stp
stop stopList50 docOrig\JavaidMT.txt > docStop\JavaidMT.stp
stop stopList50 docOrig\JiangS.txt > docStop\JiangS.stp
stop stopList50 docOrig\JohalS.txt > docStop\JohalS.stp
stop stopList50 docOrig\KallayT.txt > docStop\KallayT.stp
stop stopList50 docOrig\KhanS.txt > docStop\KhanS.stp
stop stopList50 docOrig\KhayumM.txt > docStop\KhayumM.stp
stop stopList50 docOrig\KijakM.txt > docStop\KijakM.stp
stop stopList50 docOrig\KoL.txt > docStop\KoL.stp
stop stopList50 docOrig\KupusamyS.txt > docStop\KupusamyS.stp
stop stopList50 docOrig\LaiYK.txt > docStop\LaiYK.stp
stop stopList50 docOrig\LamC.txt > docStop\LamC.stp
stop stopList50 docOrig\LamD.txt > docStop\LamD.stp
stop stopList50 docOrig\LauEWF.txt > docStop\LauEWF.stp
stop stopList50 docOrig\LeongJ.txt > docStop\LeongJ.stp
stop stopList50 docOrig\LiC.txt > docStop\LiC.stp
stop stopList50 docOrig\LimCL.txt > docStop\LimCL.stp
stop stopList50 docOrig\LimSL.txt > docStop\LimSL.stp
stop stopList50 docOrig\LimS.txt > docStop\LimS.stp
stop stopList50 docOrig\LingLH.txt > docStop\LingLH.stp
stop stopList50 docOrig\LoH.txt > docStop\LoH.stp
stop stopList50 docOrig\LokCY.txt > docStop\LokCY.stp
stop stopList50 docOrig\LoV.txt > docStop\LoV.stp
stop stopList50 docOrig\McCardleR.txt > docStop\McCardleR.stp
stop stopList50 docOrig\McKayM.txt > docStop\McKayM.stp
stop stopList50 docOrig\MohdNasir.txt > docStop\MohdNasir.stp
stop stopList50 docOrig\MohdSarit.txt > docStop\MohdSarit.stp
stop stopList50 docOrig\MoN.txt > docStop\MoN.stp
stop stopList50 docOrig\MorganC.txt > docStop\MorganC.stp
stop stopList50 docOrig\MurrianR.txt > docStop\MurrianR.stp
stop stopList50 docOrig\NelsonJ.txt > docStop\NelsonJ.stp
stop stopList50 docOrig\NgTA.txt > docStop\NgTA.stp
stop stopList50 docOrig\NgWC.txt > docStop\NgWC.stp
stop stopList50 docOrig\NyagoA.txt > docStop\NyagoA.stp
stop stopList50 docOrig\OkorieV.txt > docStop\OkorieV.stp
stop stopList50 docOrig\OlomofeO.txt > docStop\OlomofeO.stp
stop stopList50 docOrig\PalmerG.txt > docStop\PalmerG.stp
stop stopList50 docOrig\PangCVA.txt > docStop\PangCVA.stp
stop stopList50 docOrig\PangG.txt > docStop\PangG.stp
stop stopList50 docOrig\PargeterA.txt > docStop\PargeterA.stp
stop stopList50 docOrig\PonsamritN.txt > docStop\PonsamritN.stp
stop stopList50 docOrig\PopadapoulosK.txt > docStop\PopadapoulosK.stp
stop stopList50 docOrig\RajaI.txt > docStop\RajaI.stp
stop stopList50 docOrig\RobertsonA.txt > docStop\RobertsonA.stp
stop stopList50 docOrig\RobertsSM.txt > docStop\RobertsSM.stp
stop stopList50 docOrig\RossiterJ.txt > docStop\RossiterJ.stp
stop stopList50 docOrig\SamuelPNEW.txt > docStop\SamuelPNEW.stp
stop stopList50 docOrig\SamuelP.txt > docStop\SamuelP.stp
stop stopList50 docOrig\SchutzP.txt > docStop\SchutzP.stp
stop stopList50 docOrig\ShahJ.txt > docStop\ShahJ.stp
stop stopList50 docOrig\SodenJ.txt > docStop\SodenJ.stp
stop stopList50 docOrig\SoonV.txt > docStop\SoonV.stp
stop stopList50 docOrig\specification-Lam.txt > docStop\specification-Lam.stp
stop stopList50 docOrig\SriskandarajahA.txt > docStop\SriskandarajahA.stp
stop stopList50 docOrig\SwantstonD.txt > docStop\SwantstonD.stp
stop stopList50 docOrig\TanPSN.txt > docStop\TanPSN.stp
stop stopList50 docOrig\TanSMS.txt > docStop\TanSMS.stp
stop stopList50 docOrig\TiongY.txt > docStop\TiongY.stp
stop stopList50 docOrig\TngL.txt > docStop\TngL.stp
stop stopList50 docOrig\TohTS.txt > docStop\TohTS.stp
stop stopList50 docOrig\TomlinsonM.txt > docStop\TomlinsonM.stp
stop stopList50 docOrig\TowersL.txt > docStop\TowersL.stp
stop stopList50 docOrig\TsangB.txt > docStop\TsangB.stp
stop stopList50 docOrig\WangMY.txt > docStop\WangMY.stp
stop stopList50 docOrig\WangWS.txt > docStop\WangWS.stp
stop stopList50 docOrig\WangW.txt > docStop\WangW.stp
stop stopList50 docOrig\WilliamsJ.txt > docStop\WilliamsJ.stp
stop stopList50 docOrig\WongCY.txt > docStop\WongCY.stp
stop stopList50 docOrig\WongK.txt > docStop\WongK.stp
stop stopList50 docOrig\WongWS.txt > docStop\WongWS.stp
stop stopList50 docOrig\YaseenU.txt > docStop\YaseenU.stp
stop stopList50 docOrig\YeapKS.txt > docStop\YeapKS.stp
stop stopList50 docOrig\YiuMLM.txt > docStop\YiuMLM.stp
stop stopList50 docOrig\ZhangJ.txt > docStop\ZhangJ.stp
